# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_loginWindow(object):
    def setupUi(self, loginWindow):
        loginWindow.setObjectName("loginWindow")
        loginWindow.resize(573, 573)
        self.header = QtWidgets.QLabel(loginWindow)
        self.header.setGeometry(QtCore.QRect(220, 320, 161, 40))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.header.setFont(font)
        self.header.setObjectName("header")
        self.usuarioLabel = QtWidgets.QLabel(loginWindow)
        self.usuarioLabel.setGeometry(QtCore.QRect(70, 390, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.usuarioLabel.setFont(font)
        self.usuarioLabel.setObjectName("usuarioLabel")
        self.senhaLabel = QtWidgets.QLabel(loginWindow)
        self.senhaLabel.setGeometry(QtCore.QRect(70, 460, 91, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.senhaLabel.setFont(font)
        self.senhaLabel.setObjectName("senhaLabel")
        self.usuarioInput = QtWidgets.QLineEdit(loginWindow)
        self.usuarioInput.setGeometry(QtCore.QRect(200, 370, 281, 41))
        self.usuarioInput.setObjectName("usuarioInput")
        self.senhaInput = QtWidgets.QLineEdit(loginWindow)
        self.senhaInput.setGeometry(QtCore.QRect(200, 440, 281, 41))
        self.senhaInput.setEchoMode(QtWidgets.QLineEdit.Password)
        self.senhaInput.setObjectName("senhaInput")
        self.entrarBotao = QtWidgets.QPushButton(loginWindow)
        self.entrarBotao.setGeometry(QtCore.QRect(240, 510, 111, 41))
        self.entrarBotao.setObjectName("entrarBotao")
        self.label = QtWidgets.QLabel(loginWindow)
        self.label.setGeometry(QtCore.QRect(0, 10, 561, 291))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("imagens/logo_nova.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")

        self.retranslateUi(loginWindow)
        QtCore.QMetaObject.connectSlotsByName(loginWindow)

    def retranslateUi(self, loginWindow):
        _translate = QtCore.QCoreApplication.translate
        loginWindow.setWindowTitle(_translate("loginWindow", "Sistema Emissor de Notas Fiscais Eletrônicas"))
        self.header.setText(_translate("loginWindow", "RETAGUARDA"))
        self.usuarioLabel.setText(_translate("loginWindow", "Usuário"))
        self.senhaLabel.setText(_translate("loginWindow", "Senha"))
        self.entrarBotao.setText(_translate("loginWindow", "ENTRAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    loginWindow = QtWidgets.QDialog()
    ui = Ui_loginWindow()
    ui.setupUi(loginWindow)
    loginWindow.show()
    sys.exit(app.exec_())
